{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "%load_ext autoreload\n",
    "%autoreload 2"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## One featurizer to rule them all?\n",
    "Contrary to many other machine learning domains, _molecular_ featurization (i.e. the process of transforming a molecule into a vector) lacks a good default. It remains unclear how we can effectively capture the richness of molecular data in a unified representation and what works best heavily depends on the nature and constraints of the task you are trying to model. It is therefore good practice to try different featurization schemes: From structural fingerprints, to physico-chemical descriptors and pre-trained embeddings.\n",
    "\n",
    "## Don't take our word for it\n",
    "To demonstrate the impact a featurizer can have, we setup two simple benchmarks.\n",
    "1. To demonstrate the impact on modeling, we will use two datasets from [MoleculeNet](https://moleculenet.org/datasets-1).\n",
    "2. To demonstrate the impact on search, we will use the [RDKit Benchmarking Platform](https://github.com/rdkit/benchmarking_platform).\n",
    "\n",
    "We will compare the performance of three different featurizers:\n",
    "- **ECFP6** [1]: Binary, circular fingerprints where each bit indicates the presence of particular substructures of a radius up to 3 bonds away from an atom.\n",
    "- **Mordred** [2]: Continuous descriptors with more than 1800 2D and 3D descriptors.\n",
    "- **ChemBERTa** [3]: Learned representations from a pre-trained SMILES transformer model.\n",
    "\n",
    "### Modeling\n",
    "We will compare the performance on two datasets using scikit-learn [AutoML](https://github.com/automl/auto-sklearn) [4, 5] models."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import datamol as dm\n",
    "import autosklearn.classification\n",
    "import autosklearn.regression\n",
    "from sklearn.metrics import mean_absolute_error, roc_auc_score\n",
    "from sklearn.model_selection import GroupShuffleSplit\n",
    "from rdkit.Chem import SaltRemover\n",
    "\n",
    "from molfeat.trans.fp import FPVecTransformer\n",
    "from molfeat.trans.pretrained.hf_transformers import PretrainedHFTransformer"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "def load_dataset(uri: str, readout_col: str):\n",
    "    \"\"\"Loads the MoleculeNet dataset\"\"\"\n",
    "    df = pd.read_csv(uri)\n",
    "    smiles = df[\"smiles\"].values\n",
    "    y = df[readout_col].values\n",
    "    return smiles, y\n",
    "\n",
    "\n",
    "def preprocess_smiles(smi):\n",
    "    \"\"\"Preprocesses the SMILES string\"\"\"\n",
    "    with dm.without_rdkit_log():\n",
    "        mol = dm.to_mol(smi, ordered=True, sanitize=False)\n",
    "        mol = dm.sanitize_mol(mol)\n",
    "        if mol is None: \n",
    "            return\n",
    "        \n",
    "        mol = dm.standardize_mol(mol, disconnect_metals=True)\n",
    "        remover = SaltRemover.SaltRemover()\n",
    "        mol = remover.StripMol(mol, dontRemoveEverything=True)\n",
    "\n",
    "    return dm.to_smiles(mol)\n",
    "\n",
    "\n",
    "def scaffold_split(smiles):\n",
    "    \"\"\"In line with common practice, we will use the scaffold split to evaluate our models\"\"\"\n",
    "    scaffolds = [dm.to_smiles(dm.to_scaffold_murcko(dm.to_mol(smi))) for smi in smiles]\n",
    "    splitter = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)\n",
    "    return next(splitter.split(smiles, groups=scaffolds))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/google/auth/_default.py:78: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a \"quota exceeded\" or \"API not enabled\" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds. \n",
      "  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)\n"
     ]
    }
   ],
   "source": [
    "# Setup the featurizers\n",
    "trans_ecfp = FPVecTransformer(kind=\"ecfp:6\", n_jobs=-1)\n",
    "trans_mordred = FPVecTransformer(kind=\"mordred\", replace_nan=True, n_jobs=-1)\n",
    "trans_chemberta = PretrainedHFTransformer(kind='ChemBERTa-77M-MLM', notation='smiles')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Lipophilicity\n",
    "Lipophilicity is a regression task with 4200 molecules"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce\n",
      "  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)\n",
      "/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py:700: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.\n",
      "  warnings.warn(\n",
      "/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce\n",
      "  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)\n",
      "/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce\n",
      "  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)\n",
      "/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce\n",
      "  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)\n",
      "/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce\n",
      "  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)\n",
      "/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce\n",
      "  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)\n",
      "/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce\n",
      "  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)\n",
      "/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce\n",
      "  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "8e7e14b32f584b78935c5dc51874c686",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "  0%|          | 0/4200 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "c3765976341542c694811502902ac9c5",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "  0%|          | 0/4200 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "# Prepare the Lipophilicity dataset\n",
    "smiles, y_true = load_dataset(\"https://deepchemdata.s3-us-west-1.amazonaws.com/datasets/Lipophilicity.csv\", \"exp\")\n",
    "smiles = np.array([preprocess_smiles(smi) for smi in smiles])\n",
    "smiles = np.array([smi for smi in smiles if smi != \"\"])\n",
    "\n",
    "X = {\n",
    "    \"ECFP\": trans_ecfp(smiles),\n",
    "    \"Mordred\": trans_mordred(smiles),\n",
    "    \"ChemBERTa\": trans_chemberta(smiles),\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[WARNING] [2023-03-21 09:43:37,219:Client-EnsembleBuilder] No runs were available to build an ensemble from\n",
      "[WARNING] [2023-03-21 09:43:52,005:Client-EnsembleBuilder] No runs were available to build an ensemble from\n",
      "[WARNING] [2023-03-21 09:43:53,508:Client-EnsembleBuilder] No runs were available to build an ensemble from\n",
      "[WARNING] [2023-03-21 09:49:31,814:Client-EnsembleBuilder] No runs were available to build an ensemble from\n",
      "[WARNING] [2023-03-21 09:49:35,671:Client-EnsembleBuilder] No runs were available to build an ensemble from\n",
      "[WARNING] [2023-03-21 09:49:45,916:Client-EnsembleBuilder] No runs were available to build an ensemble from\n",
      "[WARNING] [2023-03-21 09:55:25,854:Client-EnsembleBuilder] No runs were available to build an ensemble from\n",
      "[WARNING] [2023-03-21 09:55:31,098:Client-EnsembleBuilder] No runs were available to build an ensemble from\n",
      "[WARNING] [2023-03-21 09:56:08,207:Client-EnsembleBuilder] No runs were available to build an ensemble from\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "{'ECFP': 0.6889895591995786,\n",
       " 'Mordred': 0.5481806419968572,\n",
       " 'ChemBERTa': 0.7432117051810577}"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# To make the output less verbose: \n",
    "os.environ[\"TOKENIZERS_PARALLELISM\"] = \"false\"\n",
    "\n",
    "# Train a model\n",
    "train_ind, test_ind = scaffold_split(smiles)\n",
    "\n",
    "scores = {}\n",
    "for name, feats in X.items():\n",
    "    \n",
    "    # Train\n",
    "    automl = autosklearn.regression.AutoSklearnRegressor(\n",
    "        memory_limit=24576, \n",
    "        time_left_for_this_task=360,\n",
    "        n_jobs=1\n",
    "    )\n",
    "    automl.fit(feats[train_ind], y_true[train_ind])\n",
    "    \n",
    "    # Predict and evaluate\n",
    "    y_hat = automl.predict(feats[test_ind])\n",
    "    \n",
    "    # Evaluate\n",
    "    mae = mean_absolute_error(y_true[test_ind], y_hat)\n",
    "    scores[name] = mae\n",
    "\n",
    "scores"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### ClinTox"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/datamol/_sanifix4.py\", line 118, in sanifix\n",
      "    Chem.SanitizeMol(cp)\n",
      "rdkit.Chem.rdchem.AtomValenceException: Explicit valence for atom # 0 N, 5, is greater than permitted\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/logging/__init__.py\", line 1083, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/logging/__init__.py\", line 927, in format\n",
      "    return fmt.format(record)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/logging/__init__.py\", line 663, in format\n",
      "    record.message = record.getMessage()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/logging/__init__.py\", line 367, in getMessage\n",
      "    msg = msg % self.args\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 725, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "    handle._run()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 513, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 502, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 409, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 729, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 540, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2961, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3016, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3221, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3400, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3460, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_11612/2689847368.py\", line 3, in <module>\n",
      "    smiles = np.array([preprocess_smiles(smi) for smi in smiles])\n",
      "  File \"/tmp/ipykernel_11612/2689847368.py\", line 3, in <listcomp>\n",
      "    smiles = np.array([preprocess_smiles(smi) for smi in smiles])\n",
      "  File \"/tmp/ipykernel_11612/2436713256.py\", line 13, in preprocess_smiles\n",
      "    mol = dm.sanitize_mol(mol)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/datamol/mol.py\", line 323, in sanitize_mol\n",
      "    mol = _sanifix4.sanifix(mol)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/datamol/_sanifix4.py\", line 121, in sanifix\n",
      "    logging.debug(e, Chem.MolToSmiles(m))\n",
      "Message: AtomValenceException('Explicit valence for atom # 0 N, 5, is greater than permitted')\n",
      "Arguments: ('[NH4][Pt]([NH4])(Cl)Cl',)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/datamol/_sanifix4.py\", line 118, in sanifix\n",
      "    Chem.SanitizeMol(cp)\n",
      "rdkit.Chem.rdchem.KekulizeException: Can't kekulize mol.  Unkekulized atoms: 21\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/logging/__init__.py\", line 1083, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/logging/__init__.py\", line 927, in format\n",
      "    return fmt.format(record)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/logging/__init__.py\", line 663, in format\n",
      "    record.message = record.getMessage()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/logging/__init__.py\", line 367, in getMessage\n",
      "    msg = msg % self.args\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 725, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "    handle._run()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 513, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 502, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 409, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 729, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 540, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2961, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3016, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3221, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3400, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3460, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_11612/2689847368.py\", line 3, in <module>\n",
      "    smiles = np.array([preprocess_smiles(smi) for smi in smiles])\n",
      "  File \"/tmp/ipykernel_11612/2689847368.py\", line 3, in <listcomp>\n",
      "    smiles = np.array([preprocess_smiles(smi) for smi in smiles])\n",
      "  File \"/tmp/ipykernel_11612/2436713256.py\", line 13, in preprocess_smiles\n",
      "    mol = dm.sanitize_mol(mol)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/datamol/mol.py\", line 323, in sanitize_mol\n",
      "    mol = _sanifix4.sanifix(mol)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/datamol/_sanifix4.py\", line 121, in sanifix\n",
      "    logging.debug(e, Chem.MolToSmiles(m))\n",
      "Message: KekulizeException(\"Can't kekulize mol.  Unkekulized atoms: 21\")\n",
      "Arguments: ('O=c1c(CCS(=O)c2ccccc2)c(=O)n(c2ccccc2)n1c1ccccc1',)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/datamol/_sanifix4.py\", line 118, in sanifix\n",
      "    Chem.SanitizeMol(cp)\n",
      "rdkit.Chem.rdchem.AtomValenceException: Explicit valence for atom # 81 N, 4, is greater than permitted\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/logging/__init__.py\", line 1083, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/logging/__init__.py\", line 927, in format\n",
      "    return fmt.format(record)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/logging/__init__.py\", line 663, in format\n",
      "    record.message = record.getMessage()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/logging/__init__.py\", line 367, in getMessage\n",
      "    msg = msg % self.args\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 725, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "    handle._run()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 513, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 502, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 409, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 729, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 540, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2961, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3016, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3221, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3400, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3460, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_11612/2689847368.py\", line 3, in <module>\n",
      "    smiles = np.array([preprocess_smiles(smi) for smi in smiles])\n",
      "  File \"/tmp/ipykernel_11612/2689847368.py\", line 3, in <listcomp>\n",
      "    smiles = np.array([preprocess_smiles(smi) for smi in smiles])\n",
      "  File \"/tmp/ipykernel_11612/2436713256.py\", line 13, in preprocess_smiles\n",
      "    mol = dm.sanitize_mol(mol)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/datamol/mol.py\", line 323, in sanitize_mol\n",
      "    mol = _sanifix4.sanifix(mol)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/datamol/_sanifix4.py\", line 121, in sanifix\n",
      "    logging.debug(e, Chem.MolToSmiles(m))\n",
      "Message: AtomValenceException('Explicit valence for atom # 81 N, 4, is greater than permitted')\n",
      "Arguments: ('CC1=C2N3[C@@H]4[C@H](CC(N)=O)[C@@]2(C)CCC(=O)NC[C@@H](C)OP(=O)([O-])O[C@H]2[C@@H](O)[C@H](O[C@@H]2CO)N2C=N(c5cc(C)c(C)cc52)[Co+]325(O)N3=C1[C@@H](CCC(N)=O)C(C)(C)C3=CC1=N2C(=C(C)C2=N5[C@]4(C)[C@@](C)(CC(N)=O)[C@@H]2CCC(N)=O)[C@@](C)(CC(N)=O)[C@@H]1CCC(N)=O',)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/datamol/_sanifix4.py\", line 118, in sanifix\n",
      "    Chem.SanitizeMol(cp)\n",
      "rdkit.Chem.rdchem.AtomValenceException: Explicit valence for atom # 82 N, 4, is greater than permitted\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/logging/__init__.py\", line 1083, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/logging/__init__.py\", line 927, in format\n",
      "    return fmt.format(record)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/logging/__init__.py\", line 663, in format\n",
      "    record.message = record.getMessage()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/logging/__init__.py\", line 367, in getMessage\n",
      "    msg = msg % self.args\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 725, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "    handle._run()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 513, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 502, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 409, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 729, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 540, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2961, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3016, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3221, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3400, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3460, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_11612/2689847368.py\", line 3, in <module>\n",
      "    smiles = np.array([preprocess_smiles(smi) for smi in smiles])\n",
      "  File \"/tmp/ipykernel_11612/2689847368.py\", line 3, in <listcomp>\n",
      "    smiles = np.array([preprocess_smiles(smi) for smi in smiles])\n",
      "  File \"/tmp/ipykernel_11612/2436713256.py\", line 13, in preprocess_smiles\n",
      "    mol = dm.sanitize_mol(mol)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/datamol/mol.py\", line 323, in sanitize_mol\n",
      "    mol = _sanifix4.sanifix(mol)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/datamol/_sanifix4.py\", line 121, in sanifix\n",
      "    logging.debug(e, Chem.MolToSmiles(m))\n",
      "Message: AtomValenceException('Explicit valence for atom # 82 N, 4, is greater than permitted')\n",
      "Arguments: ('CC1=C2N3[C@@H]4[C@H](CC(N)=O)[C@@]2(C)CCC(=O)NC[C@@H](C)OP(=O)(O)O[C@H]2[C@@H](O)[C@H](O[C@@H]2CO)N2C=N(c5cc(C)c(C)cc52)[Co]325(C#N)N3=C1[C@@H](CCC(N)=O)C(C)(C)C3=CC1=N2C(=C(C)C2=N5[C@]4(C)[C@@](C)(CC(N)=O)[C@@H]2CCC(N)=O)[C@@](C)(CC(N)=O)[C@@H]1CCC(N)=O',)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/datamol/_sanifix4.py\", line 118, in sanifix\n",
      "    Chem.SanitizeMol(cp)\n",
      "rdkit.Chem.rdchem.KekulizeException: Can't kekulize mol.  Unkekulized atoms: 17\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/logging/__init__.py\", line 1083, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/logging/__init__.py\", line 927, in format\n",
      "    return fmt.format(record)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/logging/__init__.py\", line 663, in format\n",
      "    record.message = record.getMessage()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/logging/__init__.py\", line 367, in getMessage\n",
      "    msg = msg % self.args\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 725, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "    handle._run()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 513, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 502, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 409, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 729, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 540, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2961, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3016, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3221, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3400, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3460, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_11612/2689847368.py\", line 3, in <module>\n",
      "    smiles = np.array([preprocess_smiles(smi) for smi in smiles])\n",
      "  File \"/tmp/ipykernel_11612/2689847368.py\", line 3, in <listcomp>\n",
      "    smiles = np.array([preprocess_smiles(smi) for smi in smiles])\n",
      "  File \"/tmp/ipykernel_11612/2436713256.py\", line 13, in preprocess_smiles\n",
      "    mol = dm.sanitize_mol(mol)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/datamol/mol.py\", line 323, in sanitize_mol\n",
      "    mol = _sanifix4.sanifix(mol)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/datamol/_sanifix4.py\", line 121, in sanifix\n",
      "    logging.debug(e, Chem.MolToSmiles(m))\n",
      "Message: KekulizeException(\"Can't kekulize mol.  Unkekulized atoms: 17\")\n",
      "Arguments: ('CCCCc1c(=O)n(c2ccccc2)n(c2ccc(O)cc2)c1=O',)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/datamol/_sanifix4.py\", line 118, in sanifix\n",
      "    Chem.SanitizeMol(cp)\n",
      "rdkit.Chem.rdchem.KekulizeException: Can't kekulize mol.  Unkekulized atoms: 16\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/logging/__init__.py\", line 1083, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/logging/__init__.py\", line 927, in format\n",
      "    return fmt.format(record)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/logging/__init__.py\", line 663, in format\n",
      "    record.message = record.getMessage()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/logging/__init__.py\", line 367, in getMessage\n",
      "    msg = msg % self.args\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 725, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "    handle._run()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 513, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 502, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 409, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 729, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 540, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2961, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3016, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3221, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3400, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3460, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_11612/2689847368.py\", line 3, in <module>\n",
      "    smiles = np.array([preprocess_smiles(smi) for smi in smiles])\n",
      "  File \"/tmp/ipykernel_11612/2689847368.py\", line 3, in <listcomp>\n",
      "    smiles = np.array([preprocess_smiles(smi) for smi in smiles])\n",
      "  File \"/tmp/ipykernel_11612/2436713256.py\", line 13, in preprocess_smiles\n",
      "    mol = dm.sanitize_mol(mol)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/datamol/mol.py\", line 323, in sanitize_mol\n",
      "    mol = _sanifix4.sanifix(mol)\n",
      "  File \"/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/datamol/_sanifix4.py\", line 121, in sanifix\n",
      "    logging.debug(e, Chem.MolToSmiles(m))\n",
      "Message: KekulizeException(\"Can't kekulize mol.  Unkekulized atoms: 16\")\n",
      "Arguments: ('CCCCc1c(=O)n(c2ccccc2)n(c2ccccc2)c1=O',)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[10:36:46] Unusual charge on atom 0 number of radical electrons set to zero\n",
      "[10:36:48] Unusual charge on atom 0 number of radical electrons set to zero\n",
      "[10:36:48] Unusual charge on atom 0 number of radical electrons set to zero\n",
      "[10:36:48] Unusual charge on atom 0 number of radical electrons set to zero\n",
      "[10:36:48] Unusual charge on atom 0 number of radical electrons set to zero\n",
      "/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce\n",
      "  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)\n",
      "/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py:700: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.\n",
      "  warnings.warn(\n",
      "/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce\n",
      "  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)\n",
      "/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce\n",
      "  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)\n",
      "/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce\n",
      "  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)\n",
      "/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce\n",
      "  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)\n",
      "/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce\n",
      "  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)\n",
      "/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce\n",
      "  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)\n",
      "/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce\n",
      "  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)\n",
      "/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce\n",
      "  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)\n",
      "/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce\n",
      "  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)\n",
      "/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce\n",
      "  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)\n",
      "/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce\n",
      "  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)\n",
      "/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce\n",
      "  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)\n",
      "/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce\n",
      "  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)\n",
      "/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce\n",
      "  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)\n",
      "/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce\n",
      "  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)\n",
      "/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce\n",
      "  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)\n",
      "/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce\n",
      "  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)\n",
      "/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce\n",
      "  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)\n",
      "/home/cas/local/conda/envs/molfeat-benchmark/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce\n",
      "  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "15abbe63ff824634a6e21eb6b6ddd474",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "  0%|          | 0/1478 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "b98d4df2757542eea40f9e990f70e178",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "  0%|          | 0/1478 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "# Prepare the ClinTox dataset\n",
    "smiles, y_true = load_dataset(\"https://deepchemdata.s3-us-west-1.amazonaws.com/datasets/clintox.csv.gz\", \"CT_TOX\")\n",
    "smiles = np.array([preprocess_smiles(smi) for smi in smiles])\n",
    "smiles = np.array([smi for smi in smiles if smi is not None])\n",
    "\n",
    "X = {\n",
    "    \"ECFP\": trans_ecfp(smiles),\n",
    "    \"Mordred\": trans_mordred(smiles),\n",
    "    \"ChemBERTa\": trans_chemberta(smiles),\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[WARNING] [2023-03-21 10:49:24,650:Client-EnsembleBuilder] No models better than random - using Dummy losses!\n",
      "\tModels besides current dummy model: 0\n",
      "\tDummy models: 1\n",
      "[WARNING] [2023-03-21 10:49:40,878:Client-EnsembleBuilder] No models better than random - using Dummy losses!\n",
      "\tModels besides current dummy model: 0\n",
      "\tDummy models: 1\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "{'ECFP': 0.47138888888888886,\n",
       " 'Mordred': 0.4252777777777778,\n",
       " 'ChemBERTa': 0.3705555555555555}"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# To make the output less verbose: \n",
    "os.environ[\"TOKENIZERS_PARALLELISM\"] = \"false\"\n",
    "\n",
    "# Train a model\n",
    "train_ind, test_ind = scaffold_split(smiles)\n",
    "\n",
    "scores = {}\n",
    "for name, feats in X.items():\n",
    "    \n",
    "    # Train\n",
    "    automl = autosklearn.classification.AutoSklearnClassifier(\n",
    "        memory_limit=24576, \n",
    "        time_left_for_this_task=360,\n",
    "        n_jobs=1\n",
    "    )\n",
    "    automl.fit(feats[train_ind], y_true[train_ind])\n",
    "    \n",
    "    # Predict and evaluate\n",
    "    y_hat = automl.predict_proba(feats[test_ind])\n",
    "    y_hat = np.max(y_hat, axis=-1)\n",
    "    \n",
    "    # Evaluate\n",
    "    auroc = roc_auc_score(y_true[test_ind], y_hat)\n",
    "    scores[name] = auroc\n",
    "\n",
    "scores"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Conclusion\n",
    "We can see that for Lipophilicity, the Mordred featurizer proves most powerful, outperforming the next best featurizer by about 20%. For ClinTox, however, the tables have turned and it is instead ECFP that outperforms Mordred by about 10%.\n",
    "\n",
    "This shows the importance of trying different featurizers. Luckily, with Molfeat, this has just become a lot easier to do! "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Search\n",
    "We will evaluate the performance on the search task using "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# TODO"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Citations\n",
    "1. Rogers, D., & Hahn, M. (2010). Extended-connectivity fingerprints. Journal of chemical information and modeling, 50(5), 742-754.\n",
    "2. Moriwaki, H., Tian, Y. S., Kawashita, N., & Takagi, T. (2018). Mordred: a molecular descriptor calculator. Journal of cheminformatics, 10(1), 1-14.\n",
    "3. Chithrananda, S., Grand, G., & Ramsundar, B. (2020). Chemberta: Large-scale self-supervised pretraining for molecular property prediction. arXiv preprint arXiv:2010.09885.\n",
    "4. Efficient and Robust Automated Machine Learning Matthias Feurer, Aaron Klein, Katharina Eggensperger, Jost Springenberg, Manuel Blum and Frank Hutter Advances in Neural Information Processing Systems 28 (2015)\n",
    "5. Auto-Sklearn 2.0: The Next Generation Matthias Feurer, Katharina Eggensperger, Stefan Falkner, Marius Lindauer and Frank Hutter* arXiv:2007.04074 [cs.LG], 2020\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.16"
  },
  "vscode": {
   "interpreter": {
    "hash": "dd64925fe6617865d410306d2b64fa69b44b63a36aad85fd11f7d4e4dc7609f3"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
